name: saffron_clarity
description: Patient App for Gravity SDOH

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: 1.0.1
  flutter:
    sdk: flutter
  
  
  #utils
  intl: ^0.17.0
  logger: ^1.1.0
  equatable: ^2.0.3
  dartz: ^0.10.0
  cupertino_icons: ^1.0.2
  pin_code_fields: ^7.3.0
  data_table_2: 2.0.3
  webview_flutter: ^2.0.13
  uni_links: ^0.5.1
  jwt_decoder: ^2.0.1
  expandable: ^5.0.1
  carousel_slider: 4.0.0
  google_fonts: 2.1.0

  #fhir
  fhir: ^0.4.6
 

  #State management, Navigation, Localization, http requests and DI
  get: 4.1.4



  #Storage
  hive: ^2.0.5
  flutter_secure_storage: ^5.0.2
   

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
  flutter_launcher_icons: ^0.9.2
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/drawables/infinity.png"

flutter:
  uses-material-design: true

  assets:
    - assets/drawables/
    - assets/anims/
    - assets/svg/
    - assets/html/
  
